# Workflow name
name: Expand tmpfs

# Trigger on workflow_call
on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Image to Docker
    runs-on: ubuntu-latest
    env:
      IMAGE_ARTIFACT_URL: docker.io/chiragjn/soci-test-python:0.1.0
    steps:
      - name: Check
        run: |
          df -h /tmp
          sudo mount -o remount,size=10G /tmp
          df -h /tmp
