# Workflow name
name: Build and push container images

# Trigger on workflow_call
on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Image to JFrog Artifactory
    runs-on: ubuntu-latest
    env:
      IMAGE_ARTIFACT_URL: docker.io/chiragjn/soci-test-python:0.1.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to JFrog Artifactory
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: false
          file: soci-push/Dockerfile
          context: soci-push/
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_ARTIFACT_URL }}
      
      - name: Push soci index
        if: ${{ inputs.push_soci_index && inputs.platforms == 'linux/amd64' }}
        run: |
          # Get ctr and containerd
          wget https://github.com/containerd/containerd/releases/download/v1.7.27/containerd-1.7.27-linux-amd64.tar.gz
          tar -zxvf containerd-1.7.27-linux-amd64.tar.gz
          sudo cp bin/* /usr/local/bin/
          
          # Get soci
          wget https://github.com/awslabs/soci-snapshotter/releases/download/v0.9.0/soci-snapshotter-0.9.0-linux-amd64-static.tar.gz
          tar -zxvf soci-snapshotter-0.9.0-linux-amd64-static.tar.gz soci
          sudo mv soci /usr/local/bin/soci
          rm -rf soci-snapshotter-0.9.0-linux-amd64-static.tar.gz

          echo "Starting containerd"
          containerd > /dev/null 2>&1 &
          sleep 3
          ctr version > /dev/null

          # Push soci index
          echo "Creating soci index"
          soci create --platform=linux/amd64 "${{ env.IMAGE_ARTIFACT_URL }}"
          echo "Pushing soci index"
          soci push --platform=linux/amd64 "${{ env.IMAGE_ARTIFACT_URL }}"