name: Build the image 

on:
  push:
    tags:
      - test-prefix-v*

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_SHA: ${{ github.sha }}
  TAG_PREFIX: "test-prefix-v"

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set version tags
        run: |
          echo "Ref name is ${{ github.ref_name }}"
          echo "TAG_PREFIX is ${{ env.TAG_PREFIX }}"
          
          REF_NAME=${{ github.ref_name }}
          TAG_PREFIX=${{ env.TAG_PREFIX }}
          VERSION_TAG=$(echo $REF_NAME | awk -F$TAG_PREFIX '{print $2}')
          echo "Setting VERSION_TAG equal to $VERSION_TAG"
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
          
          ALT_VERSION_TAG=$(echo $VERSION_TAG | awk -F- '{print $1}')-${GITHUB_SHA::7}
          echo "Setting ALT_VERSION_TAG equal to $ALT_VERSION_TAG"
          echo "ALT_VERSION_TAG=$ALT_VERSION_TAG" >> $GITHUB_ENV
